In [1]:
import numpy as np

In [5]:
array1 = np.array(["sahir","jaman","is","my","name"])
array1

array(['sahir', 'jaman', 'is', 'my', 'name'], dtype='<U5')

In [3]:
array2= [ [ [1,2],"3d" ] ]
array2

[[[1, 2], '3d']]

In [4]:
print(type(array2))

<class 'list'>


In [6]:
print(type(array1))

<class 'numpy.ndarray'>


# Doing Numpy Best Example

In [7]:
a = np.array(45)
b = np.array([1,2,3,4,5])
c = np.array([ [1,2,3],[4,5,6] ])
d = np.array([ [ [1,2,3],[4,5,6],[7,8,9] ] ])

In [4]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
e = np.array([[[ [1,2,3],[4,5,6] ]]])
e

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [6]:
print(e.ndim)

4


In [7]:
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
